[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
# Must match your Thunderstore team name exactly
namespace = "LJIndustries"
name = "AnActualCartographer"
versionNumber = "1.2.0"
description = "Build and use a cartography table and you map the world five times as far, for that character in that world. Multiplier configurable."
websiteUrl = "https://github.com/3WiseStooges/AnActualCartographer"
containsNsfwContent = false

[package.dependencies]
"denikson-BepInExPack_Valheim" = "5.4.2350"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[[build.copy]]
source = "./package/AnActualCartographer.dll"
target = "AnActualCartographer.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["valheim"]

[publish.categories]
valheim = ["mods", "client-side", "tweaks"]
